import table from './benchmarks.json' with { type: 'json' };

/**
 * Category benchmarks derived from Olist. Generated by `pnpm derive`, committed,
 * never hand-edited. Types as `BenchmarkTable` once `@mazal/contracts` exists.
 */
export const benchmarks = table;

export type { OlistCategory } from './categories.ts';
