import type { BenchmarkTable } from '@mazal/contracts';
import table from './benchmarks.json' with { type: 'json' };

/**
 * Category benchmarks derived from Olist. Generated by `pnpm derive`, committed,
 * never hand-edited.
 *
 * The cast is not laziness and `satisfies` will not do: a JSON import widens every
 * string literal, so `source` arrives as `string` and never assigns to
 * `'olist' | 'kaggle_meta' | 'prior'`. What the compiler cannot check here,
 * `benchmarks.test.ts` checks against the real file — 62 categories, twelve metrics
 * each, ordered quartiles, `source` in the union, priors at `n: 0`.
 */
export const benchmarks = table as BenchmarkTable;

export type { OlistCategory } from '@mazal/contracts';
