import type { BenchmarkTable, SellerBenchmarkTable } from '@mazal/contracts';
import table from './benchmarks.json' with { type: 'json' };
import sellers from './seller-benchmarks.json' with { type: 'json' };

/**
 * Category benchmarks derived from Olist. Generated by `pnpm derive`, committed,
 * never hand-edited.
 *
 * The cast is not laziness and `satisfies` will not do: a JSON import widens every
 * string literal, so `source` arrives as `string` and never assigns to
 * `'olist' | 'kaggle_meta' | 'prior'`. What the compiler cannot check here,
 * `benchmarks.test.ts` checks against the real file — 62 categories, twelve metrics
 * each, ordered quartiles, `source` in the union, priors at `n: 0`.
 */
export const benchmarks = table as BenchmarkTable;

/**
 * Per-seller statistics for the 22 categories with enough qualifying sellers to
 * place a card against its competitors. Cast for the same reason as above.
 *
 * Only 22 of the 62, and only 18 of those carry `levers` — a category without
 * enough sellers gets no peer profile rather than a thin one.
 */
export const sellerBenchmarks = sellers as unknown as SellerBenchmarkTable;

export type { OlistCategory } from '@mazal/contracts';
