import type { CampaignDay, ProductCard } from "@mazal/contracts";
import type { LabelledCampaign } from "@mazal/contracts";
import case1Json from "../../../packages/sim/fixtures/demo-case1.json";
import case2Json from "../../../packages/sim/fixtures/demo-case2.json";
import accountJson from "../../../packages/sim/fixtures/demo-account.json";

/**
 * The two committed demo campaigns, read at build time straight from
 * `packages/sim/fixtures`. They are regenerated by the simulator — never copy a
 * value out of them into a component, because the copy survives the next
 * regeneration and the screen ends up disagreeing with the engine.
 *
 * The cast is the same story as `@mazal/data`: a JSON import widens every string
 * literal, so `card.offer` arrives as `string` and never assigns to `OfferType`.
 * The files are written by `pnpm sim:fixtures` against the same contract.
 */
export const demoCases = {
  /** Pre-flight: campaign #1 ran badly from day one; should campaign #2 launch? */
  case1: case1Json as unknown as LabelledCampaign,
  /** In-flight: two good weeks, then a stage broke mid-flight. */
  case2: case2Json as unknown as LabelledCampaign,
} as const;

/**
 * One seller, three products, one wallet — the account the Allocator advises on.
 *
 * The response curves the simulator generated from are deliberately NOT in this
 * file. The engine has to recover them from the days like it would for a real
 * seller, and a fixture that shipped the answer next to the question would make
 * every number on the screen unfalsifiable.
 */
export type AccountProductFixture = {
  id: string;
  card: ProductCard;
  days: CampaignDay[];
  currentSpend: number;
};

export const demoAccount = accountJson as unknown as {
  seed: number;
  products: AccountProductFixture[];
};
