import type { LabelledCampaign } from "@mazal/contracts";
import case1Json from "../../../packages/sim/fixtures/demo-case1.json";
import case2Json from "../../../packages/sim/fixtures/demo-case2.json";

/**
 * The two committed demo campaigns, read at build time straight from
 * `packages/sim/fixtures`. They are regenerated by the simulator — never copy a
 * value out of them into a component, because the copy survives the next
 * regeneration and the screen ends up disagreeing with the engine.
 *
 * The cast is the same story as `@mazal/data`: a JSON import widens every string
 * literal, so `card.offer` arrives as `string` and never assigns to `OfferType`.
 * The files are written by `pnpm sim:fixtures` against the same contract.
 */
export const demoCases = {
  /** Pre-flight: campaign #1 ran badly from day one; should campaign #2 launch? */
  case1: case1Json as unknown as LabelledCampaign,
  /** In-flight: two good weeks, then a stage broke mid-flight. */
  case2: case2Json as unknown as LabelledCampaign,
} as const;
