import type { McpServer } from '@modelcontextprotocol/server';
import { z } from 'zod';

import { InMemoryActionLog, type ActionLog } from '../action-log.js';
import {
  buildRecoveryPlanInputSchema,
  diagnoseCampaignInputSchema,
  executePlanInputSchema,
  predictCampaignInputSchema,
} from '../schemas.js';
import { UI_RESOURCE_URI_BY_TOOL } from '../ui/resources.js';
import { buildRecoveryPlan } from './build-recovery-plan.js';
import { diagnoseCampaign } from './diagnose-campaign.js';
import { executePlan } from './execute-plan.js';
import { predictCampaign } from './predict-campaign.js';

export const MAZAL_TOOL_NAMES = [
  'diagnose_campaign',
  'predict_campaign',
  'build_recovery_plan',
  'execute_plan',
] as const;

/**
 * Deco Studio's lifecycle callback, not a Mazal tool.
 *
 * Studio invokes `ON_MCP_CONFIGURATION` on every connection create/update
 * whose configuration state or scopes changed (decocms/studio,
 * `apps/api/src/tools/connection/{create,update}.ts`), and surfaces
 * "Tool ON_MCP_CONFIGURATION not found" when the server lacks it. Deco-native
 * apps get it generated by their runtime (`packages/runtime/src/tools.ts`) to
 * fan out to `configuration.onChange`/`onInstall` handlers; this server has no
 * configuration to react to, so the faithful implementation is to accept the
 * documented payload and return the documented empty object. The `vault`
 * field carries a Studio workload token — never log or echo it.
 */
const onMcpConfigurationInputSchema = z.object({
  state: z.unknown(),
  scopes: z.array(z.string()),
  firstRun: z.boolean().optional(),
  vault: z
    .object({
      baseUrl: z.string(),
      org: z.string(),
      subjectConnectionId: z.string(),
      token: z.string(),
    })
    .optional(),
});

function jsonResult(value: object) {
  return {
    content: [{ type: 'text' as const, text: JSON.stringify(value) }],
    structuredContent: value as Record<string, unknown>,
  };
}

export function registerMazalTools(
  server: McpServer,
  actionLog: ActionLog = new InMemoryActionLog(),
): void {
  server.registerTool(
    'diagnose_campaign',
    {
      description: 'Diagnose the earliest broken campaign funnel stage.',
      inputSchema: diagnoseCampaignInputSchema,
      // MCP Apps (spec 2026-01-26): hosts that support `ui://` resources render
      // the tool result through this view instead of prose.
      _meta: { ui: { resourceUri: UI_RESOURCE_URI_BY_TOOL['diagnose_campaign'] } },
    },
    (input) => jsonResult(diagnoseCampaign(input)),
  );

  server.registerTool(
    'predict_campaign',
    {
      description: 'Predict a deterministic launch verdict from server benchmarks.',
      inputSchema: predictCampaignInputSchema,
      _meta: { ui: { resourceUri: UI_RESOURCE_URI_BY_TOOL['predict_campaign'] } },
    },
    (input) => jsonResult(predictCampaign(input)),
  );

  server.registerTool(
    'build_recovery_plan',
    {
      description: 'Build a recovery plan directly from a validated diagnosis.',
      inputSchema: buildRecoveryPlanInputSchema,
    },
    (input) => jsonResult(buildRecoveryPlan(input)),
  );

  server.registerTool(
    'execute_plan',
    {
      description: 'Simulate approved Mazal actions and return a deterministic receipt.',
      inputSchema: executePlanInputSchema,
    },
    (input) => jsonResult(executePlan(input, actionLog)),
  );

  server.registerTool(
    'ON_MCP_CONFIGURATION',
    {
      description: 'Deco Studio configuration callback. No-op: this server holds no configuration state.',
      inputSchema: onMcpConfigurationInputSchema,
    },
    () => jsonResult({}),
  );
}
