// ─── packages/meta/src/adapter.ts ────────────────────────────────────────
// Meta's payload in, the contract out. The only translation in the product.
//
// It exists so that no agent, route handler or component ever maps a Meta field
// to a contract field by hand. If they did, the numbers on screen would come
// from an arithmetic nothing in this repo tests, which is the failure the whole
// "every number comes from deterministic TypeScript" rule is built to prevent.

import type { CampaignDay } from '@mazal/contracts';
import type { MetaAccount, MetaEntityDays } from './account.ts';
import { incomplete, MetaInsightsError, type MissingField } from './errors.ts';
import { foldDaysByDate } from './fold.ts';
import { fromCents, parseMetaCount, parseMetaNumber, toCents } from './numbers.ts';
import {
  ACTION_ALIASES,
  type CountedAction,
  type FixtureStamp,
  type MetaAction,
  type MetaInsightsRow,
} from './types.ts';

const COUNTED: CountedAction[] = ['addToCarts', 'checkoutsInitiated', 'purchases'];

const isRecord = (v: unknown): v is Record<string, unknown> =>
  typeof v === 'object' && v !== null && !Array.isArray(v);

/** Sum every entry whose `action_type` is one of ours. Unknown types are left alone. */
function readActions(
  entries: MetaAction[],
  aliases: readonly string[],
): { total: number; unreadable: boolean } {
  let total = 0;
  let unreadable = false;

  for (const entry of entries) {
    if (!aliases.includes(entry.action_type)) continue;
    const value = parseMetaNumber(entry.value);
    if (value === null) {
      unreadable = true;
      continue;
    }
    total += value;
  }
  return { total, unreadable };
}

function actionEntries(raw: unknown): MetaAction[] | null {
  if (!Array.isArray(raw)) return null;
  const entries: MetaAction[] = [];
  for (const entry of raw) {
    if (!isRecord(entry) || typeof entry['action_type'] !== 'string') return null;
    entries.push({ action_type: entry['action_type'], value: String(entry['value'] ?? '') });
  }
  return entries;
}

function readStamp(raw: unknown): FixtureStamp | undefined {
  if (!isRecord(raw) || raw['kind'] !== 'fixture') return undefined;
  return {
    kind: 'fixture',
    generator: String(raw['generator'] ?? ''),
    derivedFrom: String(raw['derivedFrom'] ?? ''),
    note: String(raw['note'] ?? ''),
  };
}

/**
 * Normalise an insights response into the contract's `CampaignDay`.
 *
 * Hand-written rather than schema-validated: `packages/ingest` is on zod 3 and
 * `apps/mcp` is on zod 4, so a package both of them import cannot depend on
 * zod at all.
 */
export function fromMetaInsights(payload: unknown): MetaAccount {
  if (!isRecord(payload) || !Array.isArray(payload['data'])) {
    throw new MetaInsightsError(
      'META_INSIGHTS_MALFORMED',
      'Not an insights response: expected an object with a `data` array.',
    );
  }

  const warnings: string[] = [];
  const missing: MissingField[] = [];
  const rows = payload['data'] as unknown[];

  const paging = payload['paging'];
  if (isRecord(paging) && typeof paging['next'] === 'string' && paging['next'].length > 0) {
    // One page is half a campaign, and half a campaign diagnosed confidently is
    // worse than no diagnosis. Said rather than silently followed: this package
    // makes no network calls.
    warnings.push('Payload is paginated and only the first page is here (`paging.next` is set).');
  }

  const stamp = readStamp(payload['__mazal_fixture']);
  if (stamp) {
    warnings.push(
      `This payload is a committed fixture, generated by ${stamp.generator}. No Meta account was called.`,
    );
  }

  const entities = new Map<string, MetaEntityDays>();
  const unknownActions = new Set<string>();
  const campaignIds = new Set<string>();
  let currency: string | undefined;

  rows.forEach((raw, rowIndex) => {
    if (!isRecord(raw)) {
      missing.push({ rowIndex, fields: ['<row is not an object>'] });
      return;
    }
    const row = raw as unknown as MetaInsightsRow;

    const date = typeof row.date_start === 'string' ? row.date_start : undefined;
    const stop = typeof row.date_stop === 'string' ? row.date_stop : undefined;

    // An aggregated row is a range, not a day. `parseMetaCsv` drops these too,
    // and for the same reason: a thirty-day total cannot sit in a series whose
    // every other member is one day.
    if (date && stop && date !== stop) {
      warnings.push(`Dropped aggregated row (${date} to ${stop}).`);
      return;
    }

    const level: 'campaign' | 'adset' = typeof row.adset_id === 'string' ? 'adset' : 'campaign';
    const id = level === 'adset' ? row.adset_id! : row.campaign_id;
    const name = (level === 'adset' ? row.adset_name : row.campaign_name) ?? id;
    if (typeof row.campaign_id === 'string' && row.campaign_id.length > 0) campaignIds.add(row.campaign_id);

    if (typeof row.account_currency === 'string') currency ??= row.account_currency;

    const gaps: string[] = [];
    if (!date) gaps.push('date_start');
    if (typeof id !== 'string' || id.length === 0) gaps.push(level === 'adset' ? 'adset_id' : 'campaign_id');

    const spendCents = (() => {
      const value = parseMetaNumber(row.spend);
      if (value === null) {
        gaps.push('spend');
        return 0;
      }
      return toCents(value);
    })();

    const counts: Record<'impressions' | 'reach' | 'clicks', number> = {
      impressions: 0,
      reach: 0,
      clicks: 0,
    };
    for (const [field, source] of [
      ['impressions', row.impressions],
      ['reach', row.reach],
      ['clicks', row.inline_link_clicks],
    ] as const) {
      const value = parseMetaCount(source);
      if (value === null) gaps.push(field === 'clicks' ? 'inline_link_clicks' : field);
      else counts[field] = value;
    }

    // The distinction the whole adapter turns on: a missing key is a hole, an
    // empty array is a real zero. Meta omits the `action_type` of something
    // that did not happen, so a day with no sales carries `actions: []`.
    const actions = actionEntries(row.actions);
    const actionValues = actionEntries(row.action_values);
    if (actions === null) gaps.push('actions');
    if (actionValues === null) gaps.push('action_values');

    const converted: Record<CountedAction, number> = {
      addToCarts: 0,
      checkoutsInitiated: 0,
      purchases: 0,
    };
    if (actions) {
      for (const key of COUNTED) {
        const { total, unreadable } = readActions(actions, ACTION_ALIASES[key]);
        if (unreadable) gaps.push(`actions.${ACTION_ALIASES[key][0]}`);
        converted[key] = total;
      }
      for (const entry of actions) {
        const known = COUNTED.some((key) => (ACTION_ALIASES[key] as readonly string[]).includes(entry.action_type));
        if (!known) unknownActions.add(entry.action_type);
      }
    }

    let revenueCents = 0;
    if (actionValues) {
      const { total, unreadable } = readActions(actionValues, ACTION_ALIASES.purchases);
      if (unreadable) gaps.push('action_values.purchase');
      revenueCents = toCents(total);
    }

    if (gaps.length > 0) {
      missing.push({ rowIndex, ...(date ? { date } : {}), ...(id ? { entityId: id } : {}), fields: gaps });
      return;
    }

    const day: CampaignDay = {
      date: date!,
      campaignId: id,
      spend: fromCents(spendCents),
      impressions: counts.impressions,
      reach: counts.reach,
      clicks: counts.clicks,
      addToCarts: converted.addToCarts,
      checkoutsInitiated: converted.checkoutsInitiated,
      purchases: converted.purchases,
      revenue: fromCents(revenueCents),
    };

    const entity = entities.get(id);
    if (entity) entity.days.push(day);
    else entities.set(id, { id, name, level, days: [day] });
  });

  if (missing.length > 0) throw incomplete(missing);

  if (unknownActions.size > 0) {
    warnings.push(
      `Ignored ${unknownActions.size} action type${unknownActions.size === 1 ? '' : 's'} this product does not read: ${[...unknownActions].sort().join(', ')}.`,
    );
  }

  const list = [...entities.values()].map((entity) => ({
    ...entity,
    days: [...entity.days].sort((a, b) => (a.date < b.date ? -1 : a.date > b.date ? 1 : 0)),
  }));

  if (list.length === 0) {
    throw new MetaInsightsError('META_INSIGHTS_MALFORMED', 'No usable rows in the insights payload.');
  }

  if (list.length > 1) {
    // Reach is deduplicated per entity by Meta and cannot be added up: the same
    // person reached by two ad sets is one person. The total below is an upper
    // bound and the only figure in this package that is not exact.
    warnings.push(
      'Reach was summed across entities. Meta deduplicates reach within an entity but not between them, so the total is an upper bound.',
    );
  }

  /**
   * The same fold the CSV path uses, so the two routes into the engine cannot
   * disagree about what a day is.
   *
   * When every row belongs to one campaign, the total is that campaign and
   * carries its id — not the id of whichever ad set happened to be first in the
   * response. Three ad sets under one campaign are one funnel seen in pieces,
   * and the piece that was written down first is not the name of the whole.
   */
  const [onlyCampaign] = campaignIds;
  const total = foldDaysByDate(list.flatMap((entity) => entity.days)).map((day) =>
    campaignIds.size === 1 && onlyCampaign ? { ...day, campaignId: onlyCampaign } : day,
  );

  return {
    total,
    entities: list,
    ...(currency ? { currency } : {}),
    warnings,
    ...(stamp ? { fixture: stamp } : {}),
  };
}
